### ISSUE TITLE
Visual Studio crashes when using Copy Description without path

### ISSUE THREAD

**Issue by larsgregersen** [mrlacey/ErrorHelper#13] opened 2023-03-14 07:36 UTC
I'm using VS2022 17.5.0.

Copy Description works. 

When using Copy Description without path the user interface stalls for a long time and then VS crashes and disappears from screen. There are no error messages.

**Comment by mrlacey** [comment] 2023-03-14 08:20
"Assuming you mean "Search Description (without paths)" causes the error.
I'm not able to reproduce this, so it might be something in the specified error message or path that it's coming from. Cany you share a copy of an example error description that causes this?

**Comment by mrlacey** [comment] 2023-03-14 08:22
I've also just released version 2.5 which adds more error handling and so should stop whatever is causing VS to crash.

**Comment by larsgregersen** [comment] 2023-03-14 13:17
I've installed 2.5. It doesn't crash, but it doesn't search either.
When using "Search Description (without paths)" the status of VS changes to "Unable to search for error description.

The descriptions is:

declaration is incompatible with "double Triangle::getArea(int x) const" (declared at line 11 of "C:\Users\Lars\OneDrive\programming\geomalgorithms\geomalgorithms\triangle.h")

**Comment by mrlacey** [comment] 2023-03-14 21:10
I've just submitted version 2.6 to the marketplace, which includes a fix for this issue.

Let me know if you have any other issues or have other suggestions for improvements.

**Closed by mrlacey** 2023-03-14 21:10 UTC

**Comment by larsgregersen** [comment] 2023-03-15 07:50
I confirm that the problem is solved with version 2.6. Thanks for fixing the problem so quick!

I'll get back to you if I have more problems or feedback.
